// Code generated by ent, DO NOT EDIT.

package event

const (
	// Label holds the string label denoting the event type in the database.
	Label = "event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUnixTime holds the string denoting the unixtime field in the database.
	FieldUnixTime = "unix_time"
	// FieldEventName holds the string denoting the eventname field in the database.
	FieldEventName = "event_name"
	// FieldIsSilent holds the string denoting the issilent field in the database.
	FieldIsSilent = "is_silent"
	// EdgeUsername holds the string denoting the username edge name in mutations.
	EdgeUsername = "username"
	// Table holds the table name of the event in the database.
	Table = "events"
	// UsernameTable is the table that holds the username relation/edge.
	UsernameTable = "events"
	// UsernameInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UsernameInverseTable = "users"
	// UsernameColumn is the table column denoting the username relation/edge.
	UsernameColumn = "user_events"
)

// Columns holds all SQL columns for event fields.
var Columns = []string{
	FieldID,
	FieldUnixTime,
	FieldEventName,
	FieldIsSilent,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "events"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_events",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUnixTime holds the default value on creation for the "unixTime" field.
	DefaultUnixTime int
	// UnixTimeValidator is a validator for the "unixTime" field. It is called by the builders before save.
	UnixTimeValidator func(int) error
	// DefaultEventName holds the default value on creation for the "eventName" field.
	DefaultEventName string
	// DefaultIsSilent holds the default value on creation for the "isSilent" field.
	DefaultIsSilent bool
)
