// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SmartWatch_Project/ent/event"
	"SmartWatch_Project/ent/predicate"
	"SmartWatch_Project/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EventUpdate is the builder for updating Event entities.
type EventUpdate struct {
	config
	hooks    []Hook
	mutation *EventMutation
}

// Where appends a list predicates to the EventUpdate builder.
func (eu *EventUpdate) Where(ps ...predicate.Event) *EventUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetUnixTime sets the "unixTime" field.
func (eu *EventUpdate) SetUnixTime(i int) *EventUpdate {
	eu.mutation.ResetUnixTime()
	eu.mutation.SetUnixTime(i)
	return eu
}

// SetNillableUnixTime sets the "unixTime" field if the given value is not nil.
func (eu *EventUpdate) SetNillableUnixTime(i *int) *EventUpdate {
	if i != nil {
		eu.SetUnixTime(*i)
	}
	return eu
}

// AddUnixTime adds i to the "unixTime" field.
func (eu *EventUpdate) AddUnixTime(i int) *EventUpdate {
	eu.mutation.AddUnixTime(i)
	return eu
}

// SetEventName sets the "eventName" field.
func (eu *EventUpdate) SetEventName(s string) *EventUpdate {
	eu.mutation.SetEventName(s)
	return eu
}

// SetNillableEventName sets the "eventName" field if the given value is not nil.
func (eu *EventUpdate) SetNillableEventName(s *string) *EventUpdate {
	if s != nil {
		eu.SetEventName(*s)
	}
	return eu
}

// SetIsSilent sets the "isSilent" field.
func (eu *EventUpdate) SetIsSilent(b bool) *EventUpdate {
	eu.mutation.SetIsSilent(b)
	return eu
}

// SetNillableIsSilent sets the "isSilent" field if the given value is not nil.
func (eu *EventUpdate) SetNillableIsSilent(b *bool) *EventUpdate {
	if b != nil {
		eu.SetIsSilent(*b)
	}
	return eu
}

// SetUsernameID sets the "username" edge to the User entity by ID.
func (eu *EventUpdate) SetUsernameID(id int) *EventUpdate {
	eu.mutation.SetUsernameID(id)
	return eu
}

// SetNillableUsernameID sets the "username" edge to the User entity by ID if the given value is not nil.
func (eu *EventUpdate) SetNillableUsernameID(id *int) *EventUpdate {
	if id != nil {
		eu = eu.SetUsernameID(*id)
	}
	return eu
}

// SetUsername sets the "username" edge to the User entity.
func (eu *EventUpdate) SetUsername(u *User) *EventUpdate {
	return eu.SetUsernameID(u.ID)
}

// Mutation returns the EventMutation object of the builder.
func (eu *EventUpdate) Mutation() *EventMutation {
	return eu.mutation
}

// ClearUsername clears the "username" edge to the User entity.
func (eu *EventUpdate) ClearUsername() *EventUpdate {
	eu.mutation.ClearUsername()
	return eu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EventUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(eu.hooks) == 0 {
		if err = eu.check(); err != nil {
			return 0, err
		}
		affected, err = eu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EventMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = eu.check(); err != nil {
				return 0, err
			}
			eu.mutation = mutation
			affected, err = eu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(eu.hooks) - 1; i >= 0; i-- {
			if eu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = eu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EventUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EventUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EventUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *EventUpdate) check() error {
	if v, ok := eu.mutation.UnixTime(); ok {
		if err := event.UnixTimeValidator(v); err != nil {
			return &ValidationError{Name: "unixTime", err: fmt.Errorf(`ent: validator failed for field "Event.unixTime": %w`, err)}
		}
	}
	return nil
}

func (eu *EventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   event.Table,
			Columns: event.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: event.FieldID,
			},
		},
	}
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.UnixTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: event.FieldUnixTime,
		})
	}
	if value, ok := eu.mutation.AddedUnixTime(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: event.FieldUnixTime,
		})
	}
	if value, ok := eu.mutation.EventName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: event.FieldEventName,
		})
	}
	if value, ok := eu.mutation.IsSilent(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: event.FieldIsSilent,
		})
	}
	if eu.mutation.UsernameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.UsernameTable,
			Columns: []string{event.UsernameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.UsernameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.UsernameTable,
			Columns: []string{event.UsernameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// EventUpdateOne is the builder for updating a single Event entity.
type EventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventMutation
}

// SetUnixTime sets the "unixTime" field.
func (euo *EventUpdateOne) SetUnixTime(i int) *EventUpdateOne {
	euo.mutation.ResetUnixTime()
	euo.mutation.SetUnixTime(i)
	return euo
}

// SetNillableUnixTime sets the "unixTime" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableUnixTime(i *int) *EventUpdateOne {
	if i != nil {
		euo.SetUnixTime(*i)
	}
	return euo
}

// AddUnixTime adds i to the "unixTime" field.
func (euo *EventUpdateOne) AddUnixTime(i int) *EventUpdateOne {
	euo.mutation.AddUnixTime(i)
	return euo
}

// SetEventName sets the "eventName" field.
func (euo *EventUpdateOne) SetEventName(s string) *EventUpdateOne {
	euo.mutation.SetEventName(s)
	return euo
}

// SetNillableEventName sets the "eventName" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableEventName(s *string) *EventUpdateOne {
	if s != nil {
		euo.SetEventName(*s)
	}
	return euo
}

// SetIsSilent sets the "isSilent" field.
func (euo *EventUpdateOne) SetIsSilent(b bool) *EventUpdateOne {
	euo.mutation.SetIsSilent(b)
	return euo
}

// SetNillableIsSilent sets the "isSilent" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableIsSilent(b *bool) *EventUpdateOne {
	if b != nil {
		euo.SetIsSilent(*b)
	}
	return euo
}

// SetUsernameID sets the "username" edge to the User entity by ID.
func (euo *EventUpdateOne) SetUsernameID(id int) *EventUpdateOne {
	euo.mutation.SetUsernameID(id)
	return euo
}

// SetNillableUsernameID sets the "username" edge to the User entity by ID if the given value is not nil.
func (euo *EventUpdateOne) SetNillableUsernameID(id *int) *EventUpdateOne {
	if id != nil {
		euo = euo.SetUsernameID(*id)
	}
	return euo
}

// SetUsername sets the "username" edge to the User entity.
func (euo *EventUpdateOne) SetUsername(u *User) *EventUpdateOne {
	return euo.SetUsernameID(u.ID)
}

// Mutation returns the EventMutation object of the builder.
func (euo *EventUpdateOne) Mutation() *EventMutation {
	return euo.mutation
}

// ClearUsername clears the "username" edge to the User entity.
func (euo *EventUpdateOne) ClearUsername() *EventUpdateOne {
	euo.mutation.ClearUsername()
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EventUpdateOne) Select(field string, fields ...string) *EventUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Event entity.
func (euo *EventUpdateOne) Save(ctx context.Context) (*Event, error) {
	var (
		err  error
		node *Event
	)
	if len(euo.hooks) == 0 {
		if err = euo.check(); err != nil {
			return nil, err
		}
		node, err = euo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EventMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = euo.check(); err != nil {
				return nil, err
			}
			euo.mutation = mutation
			node, err = euo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(euo.hooks) - 1; i >= 0; i-- {
			if euo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = euo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, euo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Event)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from EventMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EventUpdateOne) SaveX(ctx context.Context) *Event {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EventUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EventUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *EventUpdateOne) check() error {
	if v, ok := euo.mutation.UnixTime(); ok {
		if err := event.UnixTimeValidator(v); err != nil {
			return &ValidationError{Name: "unixTime", err: fmt.Errorf(`ent: validator failed for field "Event.unixTime": %w`, err)}
		}
	}
	return nil
}

func (euo *EventUpdateOne) sqlSave(ctx context.Context) (_node *Event, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   event.Table,
			Columns: event.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: event.FieldID,
			},
		},
	}
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Event.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, event.FieldID)
		for _, f := range fields {
			if !event.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != event.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.UnixTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: event.FieldUnixTime,
		})
	}
	if value, ok := euo.mutation.AddedUnixTime(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: event.FieldUnixTime,
		})
	}
	if value, ok := euo.mutation.EventName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: event.FieldEventName,
		})
	}
	if value, ok := euo.mutation.IsSilent(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: event.FieldIsSilent,
		})
	}
	if euo.mutation.UsernameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.UsernameTable,
			Columns: []string{event.UsernameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.UsernameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.UsernameTable,
			Columns: []string{event.UsernameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Event{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
