// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SmartWatch_Project/ent/event"
	"SmartWatch_Project/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EventCreate is the builder for creating a Event entity.
type EventCreate struct {
	config
	mutation *EventMutation
	hooks    []Hook
}

// SetUnixTime sets the "unixTime" field.
func (ec *EventCreate) SetUnixTime(i int) *EventCreate {
	ec.mutation.SetUnixTime(i)
	return ec
}

// SetNillableUnixTime sets the "unixTime" field if the given value is not nil.
func (ec *EventCreate) SetNillableUnixTime(i *int) *EventCreate {
	if i != nil {
		ec.SetUnixTime(*i)
	}
	return ec
}

// SetEventName sets the "eventName" field.
func (ec *EventCreate) SetEventName(s string) *EventCreate {
	ec.mutation.SetEventName(s)
	return ec
}

// SetNillableEventName sets the "eventName" field if the given value is not nil.
func (ec *EventCreate) SetNillableEventName(s *string) *EventCreate {
	if s != nil {
		ec.SetEventName(*s)
	}
	return ec
}

// SetIsSilent sets the "isSilent" field.
func (ec *EventCreate) SetIsSilent(b bool) *EventCreate {
	ec.mutation.SetIsSilent(b)
	return ec
}

// SetNillableIsSilent sets the "isSilent" field if the given value is not nil.
func (ec *EventCreate) SetNillableIsSilent(b *bool) *EventCreate {
	if b != nil {
		ec.SetIsSilent(*b)
	}
	return ec
}

// SetUsernameID sets the "username" edge to the User entity by ID.
func (ec *EventCreate) SetUsernameID(id int) *EventCreate {
	ec.mutation.SetUsernameID(id)
	return ec
}

// SetNillableUsernameID sets the "username" edge to the User entity by ID if the given value is not nil.
func (ec *EventCreate) SetNillableUsernameID(id *int) *EventCreate {
	if id != nil {
		ec = ec.SetUsernameID(*id)
	}
	return ec
}

// SetUsername sets the "username" edge to the User entity.
func (ec *EventCreate) SetUsername(u *User) *EventCreate {
	return ec.SetUsernameID(u.ID)
}

// Mutation returns the EventMutation object of the builder.
func (ec *EventCreate) Mutation() *EventMutation {
	return ec.mutation
}

// Save creates the Event in the database.
func (ec *EventCreate) Save(ctx context.Context) (*Event, error) {
	var (
		err  error
		node *Event
	)
	ec.defaults()
	if len(ec.hooks) == 0 {
		if err = ec.check(); err != nil {
			return nil, err
		}
		node, err = ec.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EventMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ec.check(); err != nil {
				return nil, err
			}
			ec.mutation = mutation
			if node, err = ec.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ec.hooks) - 1; i >= 0; i-- {
			if ec.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ec.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ec.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Event)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from EventMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ec *EventCreate) SaveX(ctx context.Context) *Event {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ec *EventCreate) Exec(ctx context.Context) error {
	_, err := ec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ec *EventCreate) ExecX(ctx context.Context) {
	if err := ec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ec *EventCreate) defaults() {
	if _, ok := ec.mutation.UnixTime(); !ok {
		v := event.DefaultUnixTime
		ec.mutation.SetUnixTime(v)
	}
	if _, ok := ec.mutation.EventName(); !ok {
		v := event.DefaultEventName
		ec.mutation.SetEventName(v)
	}
	if _, ok := ec.mutation.IsSilent(); !ok {
		v := event.DefaultIsSilent
		ec.mutation.SetIsSilent(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ec *EventCreate) check() error {
	if _, ok := ec.mutation.UnixTime(); !ok {
		return &ValidationError{Name: "unixTime", err: errors.New(`ent: missing required field "Event.unixTime"`)}
	}
	if v, ok := ec.mutation.UnixTime(); ok {
		if err := event.UnixTimeValidator(v); err != nil {
			return &ValidationError{Name: "unixTime", err: fmt.Errorf(`ent: validator failed for field "Event.unixTime": %w`, err)}
		}
	}
	if _, ok := ec.mutation.EventName(); !ok {
		return &ValidationError{Name: "eventName", err: errors.New(`ent: missing required field "Event.eventName"`)}
	}
	if _, ok := ec.mutation.IsSilent(); !ok {
		return &ValidationError{Name: "isSilent", err: errors.New(`ent: missing required field "Event.isSilent"`)}
	}
	return nil
}

func (ec *EventCreate) sqlSave(ctx context.Context) (*Event, error) {
	_node, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ec *EventCreate) createSpec() (*Event, *sqlgraph.CreateSpec) {
	var (
		_node = &Event{config: ec.config}
		_spec = &sqlgraph.CreateSpec{
			Table: event.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: event.FieldID,
			},
		}
	)
	if value, ok := ec.mutation.UnixTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: event.FieldUnixTime,
		})
		_node.UnixTime = value
	}
	if value, ok := ec.mutation.EventName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: event.FieldEventName,
		})
		_node.EventName = value
	}
	if value, ok := ec.mutation.IsSilent(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: event.FieldIsSilent,
		})
		_node.IsSilent = value
	}
	if nodes := ec.mutation.UsernameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.UsernameTable,
			Columns: []string{event.UsernameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_events = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EventCreateBulk is the builder for creating many Event entities in bulk.
type EventCreateBulk struct {
	config
	builders []*EventCreate
}

// Save creates the Event entities in the database.
func (ecb *EventCreateBulk) Save(ctx context.Context) ([]*Event, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ecb.builders))
	nodes := make([]*Event, len(ecb.builders))
	mutators := make([]Mutator, len(ecb.builders))
	for i := range ecb.builders {
		func(i int, root context.Context) {
			builder := ecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ecb *EventCreateBulk) SaveX(ctx context.Context) []*Event {
	v, err := ecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecb *EventCreateBulk) Exec(ctx context.Context) error {
	_, err := ecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecb *EventCreateBulk) ExecX(ctx context.Context) {
	if err := ecb.Exec(ctx); err != nil {
		panic(err)
	}
}
